In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/home/raghav/codes_new/mental-health/data/raw/Mental Health Checker.csv')

In [4]:
df.head()

,Timestamp,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
0,2021/05/05 3:59:05 PM GMT+6,Female,20-26,University,single,<10,no,none,maybe,none,...,maybe,yes,yes,yes,night,yes,no,yes,no,no
1,2021/05/17 2:07:23 PM GMT+6,Male,20-26,University,married,<10,no,3+,yes,1,...,yes,no,yes,yes,night,no,no,no,no,no
2,2021/05/17 2:09:05 PM GMT+6,Female,13-19,College,single,<10,no,1,yes,1,...,yes,no,yes,yes,Afternoon,no,no,no,no,yes
3,2021/05/17 10:08:23 PM GMT+6,Female,13-19,College,single,<10,no,1,no,none,...,maybe,yes,yes,yes,night,no,no,yes,no,no
4,2021/05/17 10:35:16 PM GMT+6,Female,20-26,University,single,<10,no,3+,yes,3,...,yes,yes,yes,no,evening,yes,no,yes,yes,yes

In [12]:
df.columns

Index(['Timestamp', 'gender', 'age', 'education', 'marital', 'income', 'loan',
       'friend_no', 'friend_help', 'friend_interact', 'share_feel',
       'have_someone', 'lonely', 'bullied', 'family_support', 'compare_life',
       'social_media', 'hangout', 'home_time', 'religious', 'goal', 'suicidal',
       'sleep_disorder', 'mental_disorder', 'love_someone', 'die_someone',
       'thoughts_command', 'self_harm', 'thoughts_acted', 'thoughts_acted2',
       'thoughts_time', 'voices', 'harming_others', 'suicide',
       'suicidal_thoughts', 'therapy'],
      dtype='object')

In [11]:
df['loan'].value_counts()

no     179
yes     28
Name: loan, dtype: int64

In [14]:
df['home_time'].value_counts()

24     78
<20    43
<24    41
<15    38
<10     7
Name: home_time, dtype: int64

In [16]:
for x in df.columns:
    print(x)
    print(df[x].value_counts())
    print("*"*40)

Timestamp
2021/05/05 3:59:05 PM GMT+6     1
2021/05/20 9:26:15 PM GMT+6     1
2021/05/20 8:28:59 PM GMT+6     1
2021/05/20 8:42:07 PM GMT+6     1
2021/05/20 8:45:12 PM GMT+6     1
                               ..
2021/05/18 1:01:46 AM GMT+6     1
2021/05/18 1:03:21 AM GMT+6     1
2021/05/18 1:04:47 AM GMT+6     1
2021/05/18 1:07:16 AM GMT+6     1
2021/05/21 12:18:56 AM GMT+6    1
Name: Timestamp, Length: 207, dtype: int64
****************************************
gender
Male      113
Female     94
Name: gender, dtype: int64
****************************************
age
20-26         126
13-19          60
27-33          15
34-44           5
45 or more      1
Name: age, dtype: int64
****************************************
education
University    148
College        29
School         15
Name: education, dtype: int64
****************************************
marital
single       181
married       24
divorced       1
separated      1
Name: marital, dtype: int64
****************************************
income
<10    160
<20     20
50+      9
30+      9
<30      9
Name: income, dtype: int64
****************************************
loan
no     179
yes     28
Name: loan, dtype: int64
****************************************
friend_no
none    87
3+      70
2       19
1       16
3       15
Name: friend_no, dtype: int64
****************************************
friend_help
no       102
yes       73
maybe     32
Name: friend_help, dtype: int64
****************************************
friend_interact
none    97
2       37
3+      25
1       24
3       24
Name: friend_interact, dtype: int64
****************************************
share_feel
no       130
yes       46
maybe     30
idk        1
Name: share_feel, dtype: int64
****************************************
have_someone
no       130
yes       62
maybe     15
Name: have_someone, dtype: int64
****************************************
lonely
yes          119
sometimes     57
no            22
maybe          6
never          3
Name: lonely, dtype: int64
****************************************
bullied
yes    164
no      43
Name: bullied, dtype: int64
****************************************
family_support
no       128
yes       62
maybe     17
Name: family_support, dtype: int64
****************************************
compare_life
no     134
yes     73
Name: compare_life, dtype: int64
****************************************
social_media
3+ hours    82
<2 hours    57
<3 hours    56
<1 hour     12
Name: social_media, dtype: int64
****************************************
hangout
none    117
1        41
2        19
3+       17
3        12
Name: hangout, dtype: int64
****************************************
home_time
24     78
<20    43
<24    41
<15    38
<10     7
Name: home_time, dtype: int64
****************************************
religious
yes    110
no      97
Name: religious, dtype: int64
****************************************
goal
no       106
yes       76
maybe     25
Name: goal, dtype: int64
****************************************
suicidal
no       122
yes       45
maybe     40
Name: suicidal, dtype: int64
****************************************
sleep_disorder
yes    160
no      47
Name: sleep_disorder, dtype: int64
****************************************
mental_disorder
depression      127
stress           27
anxiety          22
Panic attack     13
Name: mental_disorder, dtype: int64
****************************************
love_someone
no       117
yes       68
maybe     22
Name: love_someone, dtype: int64
****************************************
die_someone
no       150
yes       37
maybe     20
Name: die_someone, dtype: int64
****************************************
thoughts_command
yes      123
no        46
maybe     38
Name: thoughts_command, dtype: int64
****************************************
self_harm
yes      150
no        48
maybe      9
Name: self_harm, dtype: int64
****************************************
thoughts_acted
yes    147
no      60
Name: thoughts_acted, dtype: int64
****************************************
thoughts_acted2
yes    151
no      56
Name: thoughts_acted2, dtype: int64
****************************************
thoughts_time
night        156
evening       11
Afternoon      8
morning        4
Name: thoughts_time, dtype: int64
****************************************
voices
no     146
yes     61
Name: voices, dtype: int64
****************************************
harming_others
no     145
yes     62
Name: harming_others, dtype: int64
****************************************
suicide
yes    152
no      55
Name: suicide, dtype: int64
****************************************
suicidal_thoughts
no     174
yes     33
Name: suicidal_thoughts, dtype: int64
****************************************
therapy
no     186
yes     21
Name: therapy, dtype: int64
****************************************

In [17]:
df.isna().sum()

Timestamp             0
gender                0
age                   0
education            15
marital               0
income                0
loan                  0
friend_no             0
friend_help           0
friend_interact       0
share_feel            0
have_someone          0
lonely                0
bullied               0
family_support        0
compare_life          0
social_media          0
hangout               1
home_time             0
religious             0
goal                  0
suicidal              0
sleep_disorder        0
mental_disorder      18
love_someone          0
die_someone           0
thoughts_command      0
self_harm             0
thoughts_acted        0
thoughts_acted2       0
thoughts_time        28
voices                0
harming_others        0
suicide               0
suicidal_thoughts     0
therapy               0
dtype: int64

In [22]:
df[df['education'].isna() == True]

,Timestamp,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
11,2021/05/17 10:43:08 PM GMT+6,Female,34-44,NaN,divorced,50+,yes,2,maybe,2,...,yes,no,no,no,evening,yes,no,no,no,no
15,2021/05/17 10:51:11 PM GMT+6,Female,27-33,NaN,married,<10,yes,none,no,none,...,yes,yes,no,yes,evening,no,no,yes,no,no
39,2021/05/17 11:35:19 PM GMT+6,Male,20-26,NaN,single,<20,yes,none,yes,none,...,no,yes,no,yes,night,no,yes,yes,no,yes
65,2021/05/18 12:54:46 AM GMT+6,Female,20-26,NaN,single,<10,yes,3+,yes,3,...,yes,no,yes,no,NaN,yes,no,no,no,no
67,2021/05/18 12:55:40 AM GMT+6,Female,27-33,NaN,married,50+,no,3+,no,2,...,no,yes,no,yes,night,no,no,yes,no,no
69,2021/05/18 12:57:48 AM GMT+6,Female,34-44,NaN,married,50+,no,3,no,2,...,yes,yes,yes,yes,night,no,no,yes,no,no
73,2021/05/18 1:03:21 AM GMT+6,Female,45 or more,NaN,married,50+,no,3+,yes,3+,...,yes,yes,yes,no,NaN,no,no,no,no,no
77,2021/05/18 1:09:19 AM GMT+6,Female,27-33,NaN,single,50+,no,3+,yes,3+,...,yes,no,yes,no,night,no,no,yes,no,no
78,2021/05/18 1:10:44 AM GMT+6,Female,34-44,NaN,married,30+,no,1,no,1,...,yes,yes,yes,yes,evening,no,no,no,yes,no
80,2021/05/18 1:12:23 AM GMT+6,Female,27-33,NaN,married,30+,no,3+,no,3,...,yes,no,no,yes,evening,no,no,yes,no,no
87,2021/05/18 4:19:01 AM GMT+6,Female,27-33,NaN,married,50+,no,3+,yes,3+,...,yes,no,yes,no,morning,yes,no,yes,yes,no
89,2021/05/18 4:20:25 AM GMT+6,Female,34-44,NaN,married,50+,no,3+,yes,3+,...,no,yes,no,yes,evening,no,no,yes,yes,yes
131,2021/05/20 7:57:18 PM GMT+6,Female,27-33,NaN,married,<10,no,none,no,none,...,yes,yes,no,yes,night,yes,yes,yes,no,no
162,2021/05/20 10:31:16 PM GMT+6,Male,27-33,NaN,married,30+,yes,2,yes,2,...,yes,no,yes,yes,evening,yes,yes,yes,no,no
165,2021/05/20 10:33:06 PM GMT+6,Female,27-33,NaN,single,50+,no,3+,yes,3,...,no,no,no,no,night,yes,no,yes,yes,yes

In [19]:
df.shape

(207, 36)