In [8]:
import pandas as pd

In [16]:
df = pd.read_csv('../data/raw/Mental Health Checker.csv')
label = pd.read_csv('../data/raw/Label_info.csv')

In [10]:
df.head()

,Timestamp,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
0,2021/05/05 3:59:05 PM GMT+6,Female,20-26,University,single,<10,no,none,maybe,none,...,maybe,yes,yes,yes,night,yes,no,yes,no,no
1,2021/05/17 2:07:23 PM GMT+6,Male,20-26,University,married,<10,no,3+,yes,1,...,yes,no,yes,yes,night,no,no,no,no,no
2,2021/05/17 2:09:05 PM GMT+6,Female,13-19,College,single,<10,no,1,yes,1,...,yes,no,yes,yes,Afternoon,no,no,no,no,yes
3,2021/05/17 10:08:23 PM GMT+6,Female,13-19,College,single,<10,no,1,no,none,...,maybe,yes,yes,yes,night,no,no,yes,no,no
4,2021/05/17 10:35:16 PM GMT+6,Female,20-26,University,single,<10,no,3+,yes,3,...,yes,yes,yes,no,evening,yes,no,yes,yes,yes

In [11]:
df.columns

Index(['Timestamp', 'gender', 'age', 'education', 'marital', 'income', 'loan',
       'friend_no', 'friend_help', 'friend_interact', 'share_feel',
       'have_someone', 'lonely', 'bullied', 'family_support', 'compare_life',
       'social_media', 'hangout', 'home_time', 'religious', 'goal', 'suicidal',
       'sleep_disorder', 'mental_disorder', 'love_someone', 'die_someone',
       'thoughts_command', 'self_harm', 'thoughts_acted', 'thoughts_acted2',
       'thoughts_time', 'voices', 'harming_others', 'suicide',
       'suicidal_thoughts', 'therapy'],
      dtype='object')

In [19]:
label['Question'][label['Label'] == 'gender'].values[0]

'Select your gender'

In [21]:
for x in df.iloc[:, 1:].columns:
    print("Label: ", x)
    print("Question: ", label['Question'][label['Label'] == x].values[0])
    x = df[x].unique()
    for y in x:
        print(y, end='\n')
    print("*"*40)

Label:  gender
Question:  Select your gender
Female
Male
****************************************
Label:  age
Question:  How old are you?
20-26
13-19
34-44
27-33
45 or more
****************************************
Label:  education
Question:  Education
University
College
nan
School
****************************************
Label:  marital
Question:  Marital status
single
married
divorced
separated
****************************************
Label:  income
Question:  Income
<10
<20
50+
30+
<30
****************************************
Label:  loan
Question:  Do you have any loan?
no
yes
****************************************
Label:  friend_no
Question:  How many friends do you have?
none
3+
1
2
3
****************************************
Label:  friend_help
Question:  Do you think your friends are helpful?
maybe
yes
no
****************************************
Label:  friend_interact
Question:  How many friends do you interact with in a day?
none
1
3
3+
2
****************************************
Label:  share_feel
Question:  Do you genuinely can share your thoughts and feelings to someone?
idk
yes
no
maybe
****************************************
Label:  have_someone
Question:  Do you have someone to think about that makes you feel happy ?
no
yes
maybe
****************************************
Label:  lonely
Question:  Do you feel lonely?
sometimes
no
maybe
yes
never
****************************************
Label:  bullied
Question:  Did you ever been bullied?
yes
no
****************************************
Label:  family_support
Question:  Do you think at least one member of your family supports  you no matter what?
no
yes
maybe
****************************************
Label:  compare_life
Question:  Do you compare your life with others?
no
yes
****************************************
Label:  social_media
Question:  How much time do you spend in social media in a day?
<2 hours
<1 hour
3+ hours
<3 hours
****************************************
Label:  hangout
Question:  How many days do you hangout with your friends in a week?
nan
1
2
3+
3
none
****************************************
Label:  home_time
Question:  How much time do you spend at home in a day?
24
<20
<15
<24
<10
****************************************
Label:  religious
Question:  Are you religious?
no
yes
****************************************
Label:  goal
Question:  Do you have a goal to achieve in life?
maybe
yes
no
****************************************
Label:  suicidal
Question:  Do you think your life is worth living?
no
yes
maybe
****************************************
Label:  sleep_disorder
Question:  Do you suffer from any kind of sleeping disorder?
yes
no
****************************************
Label:  mental_disorder
Question:  Do you suffer from any of these?
Panic attack
nan
depression
anxiety
stress
normal
****************************************
Label:  love_someone
Question:  Do you think you are loved by at least one person?
maybe
yes
no
****************************************
Label:  die_someone
Question:  Do you think there is someone who is unable to go on without you?
no
maybe
yes
****************************************
Label:  thoughts_command
Question:  Do your thoughts command you to act upon them?
maybe
yes
no
****************************************
Label:  self_harm
Question:  Did you ever thought of harming yourself?
yes
no
maybe
****************************************
Label:  thoughts_acted
Question:  Have you ever acted upon your thoughts?
yes
no
****************************************
Label:  thoughts_acted2
Question:  Are you having these thoughts recently which force you to act upon?
yes
no
****************************************
Label:  thoughts_time
Question:  At what time of the day do you have these thoughts?
night
Afternoon
evening
nan
morning
****************************************
Label:  voices
Question:  Did you ever hear any voice inside your head?
yes
no
****************************************
Label:  harming_others
Question:  Did you ever have any thought of harming others?
no
yes
****************************************
Label:  suicide
Question:  Did you ever thought of taking your life?
yes
no
****************************************
Label:  suicidal_thoughts
Question:  Have you told anyone that you want to take your life or harm others?
no
yes
****************************************
Label:  therapy
Question:  Did you ever receive any psychiatric/ professional help whenever you felt super down?
no
yes
****************************************

In [31]:
df.isna().sum()

Timestamp             0
gender                0
age                   0
education            15
marital               0
income                0
loan                  0
friend_no             0
friend_help           0
friend_interact       0
share_feel            0
have_someone          0
lonely                0
bullied               0
family_support        0
compare_life          0
social_media          0
hangout               1
home_time             0
religious             0
goal                  0
suicidal              0
sleep_disorder        0
mental_disorder      18
love_someone          0
die_someone           0
thoughts_command      0
self_harm             0
thoughts_acted        0
thoughts_acted2       0
thoughts_time        28
voices                0
harming_others        0
suicide               0
suicidal_thoughts     0
therapy               0
dtype: int64

In [32]:
#df[df['education'].isna() == True]

In [33]:
df.shape

(207, 36)

In [34]:
# dropping 'Timestamp' column
df.drop(['Timestamp'],axis = 1,inplace=True)

In [35]:
df.head()

,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,share_feel,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
0,Female,20-26,University,single,<10,no,none,maybe,none,idk,...,maybe,yes,yes,yes,night,yes,no,yes,no,no
1,Male,20-26,University,married,<10,no,3+,yes,1,yes,...,yes,no,yes,yes,night,no,no,no,no,no
2,Female,13-19,College,single,<10,no,1,yes,1,no,...,yes,no,yes,yes,Afternoon,no,no,no,no,yes
3,Female,13-19,College,single,<10,no,1,no,none,maybe,...,maybe,yes,yes,yes,night,no,no,yes,no,no
4,Female,20-26,University,single,<10,no,3+,yes,3,yes,...,yes,yes,yes,no,evening,yes,no,yes,yes,yes

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             207 non-null    object
 1   age                207 non-null    object
 2   education          192 non-null    object
 3   marital            207 non-null    object
 4   income             207 non-null    object
 5   loan               207 non-null    object
 6   friend_no          207 non-null    object
 7   friend_help        207 non-null    object
 8   friend_interact    207 non-null    object
 9   share_feel         207 non-null    object
 10  have_someone       207 non-null    object
 11  lonely             207 non-null    object
 12  bullied            207 non-null    object
 13  family_support     207 non-null    object
 14  compare_life       207 non-null    object
 15  social_media       207 non-null    object
 16  hangout            206 non-null    object
 17  home_time          207 non-null    object
 18  religious          207 non-null    object
 19  goal               207 non-null    object
 20  suicidal           207 non-null    object
 21  sleep_disorder     207 non-null    object
 22  mental_disorder    189 non-null    object
 23  love_someone       207 non-null    object
 24  die_someone        207 non-null    object
 25  thoughts_command   207 non-null    object
 26  self_harm          207 non-null    object
 27  thoughts_acted     207 non-null    object
 28  thoughts_acted2    207 non-null    object
 29  thoughts_time      179 non-null    object
 30  voices             207 non-null    object
 31  harming_others     207 non-null    object
 32  suicide            207 non-null    object
 33  suicidal_thoughts  207 non-null    object
 34  therapy            207 non-null    object
dtypes: object(35)
memory usage: 56.7+ KB

In [42]:
df['education'].mode()[0]

'University'

In [58]:
# handling missing values
for x in df.columns:
    if df[x].isnull().sum()>0:
        df[x].fillna(df[x].mode()[0],inplace=True)

In [71]:
[x for x in df.columns if df[x].isnull().sum()>0]

[]

In [74]:
print(df.shape)
df.head()

(207, 35)

,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,share_feel,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
0,Female,20-26,University,single,<10,no,none,maybe,none,idk,...,maybe,yes,yes,yes,night,yes,no,yes,no,no
1,Male,20-26,University,married,<10,no,3+,yes,1,yes,...,yes,no,yes,yes,night,no,no,no,no,no
2,Female,13-19,College,single,<10,no,1,yes,1,no,...,yes,no,yes,yes,Afternoon,no,no,no,no,yes
3,Female,13-19,College,single,<10,no,1,no,none,maybe,...,maybe,yes,yes,yes,night,no,no,yes,no,no
4,Female,20-26,University,single,<10,no,3+,yes,3,yes,...,yes,yes,yes,no,evening,yes,no,yes,yes,yes

In [75]:
# Label Encoding 
from sklearn import preprocessing

In [77]:
le = preprocessing.LabelEncoder()

In [79]:
for x in df.columns:
    df[x] = le.fit_transform(df[x])
    print(df[x].unique())
    print('*'*20)

[0 1]
********************
[1 0 3 2 4]
********************
[2 0 1]
********************
[3 1 0 2]
********************
[2 3 1 0 4]
********************
[0 1]
********************
[4 3 0 1 2]
********************
[0 2 1]
********************
[4 0 2 3 1]
********************
[0 3 2 1]
********************
[1 2 0]
********************
[3 2 0 4 1]
********************
[1 0]
********************
[1 2 0]
********************
[0 1]
********************
[2 1 0 3]
********************
[4 0 1 3 2]
********************
[0 3 2 4 1]
********************
[0 1]
********************
[0 2 1]
********************
[1 2 0]
********************
[1 0]
********************
[0 2 1 3]
********************
[0 2 1]
********************
[1 0 2]
********************
[0 2 1]
********************
[2 1 0]
********************
[1 0]
********************
[1 0]
********************
[3 0 1 2]
********************
[1 0]
********************
[0 1]
********************
[1 0]
********************
[0 1]
********************
[0 1]
********************

In [80]:
df.head()

,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,share_feel,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
0,0,1,2,3,2,0,4,0,4,0,...,0,2,1,1,3,1,0,1,0,0
1,1,1,2,1,2,0,3,2,0,3,...,2,1,1,1,3,0,0,0,0,0
2,0,0,0,3,2,0,0,2,0,2,...,2,1,1,1,0,0,0,0,0,1
3,0,0,0,3,2,0,0,1,4,1,...,0,2,1,1,3,0,0,1,0,0
4,0,1,2,3,2,0,3,2,2,3,...,2,2,1,0,1,1,0,1,1,1