In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/processed/processed_data2.csv')

In [3]:
print(df.shape)
df.head()

(291, 35)

,gender,age,education,marital,income,loan,friend_no,friend_help,friend_interact,share_feel,...,thoughts_command,self_harm,thoughts_acted,thoughts_acted2,thoughts_time,voices,harming_others,suicide,suicidal_thoughts,therapy
0,Female,20-26,University,single,<10,no,none,maybe,0,idk,...,maybe,yes,yes,yes,night,yes,no,yes,no,no
1,Male,20-26,University,married,<10,no,3+,yes,1,yes,...,yes,no,yes,yes,night,no,no,no,no,no
2,Female,13-19,College,single,<10,no,1,yes,1,no,...,yes,no,yes,yes,Afternoon,no,no,no,no,yes
3,Female,13-19,College,single,<10,no,1,no,0,maybe,...,maybe,yes,yes,yes,night,no,no,yes,no,no
4,Female,20-26,University,single,<10,no,3+,yes,3,yes,...,yes,yes,yes,no,evening,yes,no,yes,yes,yes

In [4]:
#no null values remaining
[x for x in df.columns if df[x].isnull().sum()>0]

[]

In [5]:
df.columns

Index(['gender', 'age', 'education', 'marital', 'income', 'loan', 'friend_no',
       'friend_help', 'friend_interact', 'share_feel', 'have_someone',
       'lonely', 'bullied', 'family_support', 'compare_life', 'social_media',
       'hangout', 'home_time', 'religious', 'goal', 'suicidal',
       'sleep_disorder', 'mental_disorder', 'love_someone', 'die_someone',
       'thoughts_command', 'self_harm', 'thoughts_acted', 'thoughts_acted2',
       'thoughts_time', 'voices', 'harming_others', 'suicide',
       'suicidal_thoughts', 'therapy'],
      dtype='object')

In [6]:
df['mental_disorder'].value_counts()

depression      153
stress           49
anxiety          43
None             30
Panic attack     16
Name: mental_disorder, dtype: int64

In [7]:
from pycaret.classification import *

- setup(df, target = 'mental_disorder') : max = 64
- setup(df, target = 'mental_disorder',feature_selection = True) : max = 58

In [8]:
group_names = []

In [8]:
s = setup(df, target = 'mental_disorder')

In [9]:
best = compare_models()

In [11]:
type(best)

sklearn.ensemble._forest.RandomForestClassifier

In [12]:
best

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=759, verbose=0,
                       warm_start=False)

### Light Gradient Boosting Machine

In [10]:
lightgbm = create_model("lightgbm")

In [11]:
tuned_lightgbm = tune_model(lightgbm,choose_better=True)

In [21]:
predict_model(tuned_lightgbm)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression,0.2988
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.2812
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.6826
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.7734
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.2940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.6807
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.7354
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,0.3166
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,None,0.2906
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.3158

In [20]:
# ensemble model
ensemble_lightgbm = ensemble_model(tuned_lightgbm)

In [17]:
#this is the best from here
predict_model(ensemble_lightgbm)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression,0.2623
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.2625
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.5783
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.7287
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.3282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.5654
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.6190
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,0.3561
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.3064
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.2560

### Dummy Classifier

In [14]:
dummy = create_model("dummy")

### Extra trees classifier

In [25]:
et = create_model("et")

In [28]:
tuned_et = tune_model(et,choose_better=True)

In [32]:
predict_model(tuned_et)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression,0.3080
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.4379
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.5393
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.7726
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.3042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.4154
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.5300
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,0.3802
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.3914
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.2897

In [33]:
ensemble_et = ensemble_model(tuned_et)

In [34]:
predict_model(ensemble_et)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression,0.2938
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.3829
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.5097
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.7703
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.3108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.3955
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.5267
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,0.3604
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.3488
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.2825

### CatBoost Classifier

In [35]:
catboost = create_model("catboost")

In [38]:
grid = {'max_depth': [3,4,5],'n_estimators':[10,100, 200, 300]}
tuned_catboost = tune_model(catboost,custom_grid=grid)

In [39]:
ensemble_catboost = ensemble_model(tuned_catboost)

In [40]:
predict_model(ensemble_catboost)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,None,0.3125
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.7812
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.4985
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.9431
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.4394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.4287
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.8338
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,0.3648
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.5028
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.3390

### Ridge

In [49]:
ridge = create_model("ridge")

In [50]:
#this is the best from here 
tuned_ridge = tune_model(ridge)

In [52]:
predict_model(tuned_ridge)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_evening,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression

In [51]:
ensemble_ridge = ensemble_model(tuned_ridge)

In [53]:
predict_model(ensemble_ridge)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression,1.0
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.7
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,1.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,1.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,1.0
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,1.0
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,1.0
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,1.0
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,1.0

### Logistic Regression

In [56]:
lr = create_model("lr")

In [57]:
tuned_lr = tune_model(lr)
predict_model(tuned_lr)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,None,0.3148
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.9338
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,anxiety,0.4622
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.9456
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.4440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.5580
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.7234
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,stress,0.4031
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.6017
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.5883

In [58]:
#this is better from here
ensemble_lr = ensemble_model(tuned_lr)

In [59]:
predict_model(ensemble_lr)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,stress,0.3341
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.8327
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.4405
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.9389
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.4341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.5511
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.6694
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,anxiety,0.3856
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.4402
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.4287

In [45]:
# blend models
blender = blend_models([ensemble_lightgbm,tuned_et])

In [46]:
predict_model(blender)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression,0.2852
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None,0.3502
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression,0.5588
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression,0.7506
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression,0.3162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression,0.4904
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression,0.5745
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression,0.3681
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression,0.3489
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None,0.2729

In [54]:

blender2 = blend_models([ensemble_lightgbm,tuned_et,tuned_ridge])

In [55]:
predict_model(blender2)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_evening,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None

#### In terms of train accuracy : blender 1 > blender 2
#### In terms of test accuracy : blender 2 > blender 1

In [60]:
blender3 = blend_models([ensemble_lightgbm,tuned_et,tuned_ridge,ensemble_lr])

In [61]:
predict_model(blender3)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_evening,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_yes,suicide_yes,suicidal_thoughts_no,therapy_no,mental_disorder,Label
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,stress,depression
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,None,None
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,stress,depression
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,depression,depression
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,depression
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,stress,depression
84,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,depression,depression
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,anxiety,depression
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,depression,depression
87,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,depression,None

In [62]:
# blender2 is best

### with fix_imbalance = True

In [64]:
df['mental_disorder'].value_counts()

depression      153
stress           49
anxiety          43
None             30
Panic attack     16
Name: mental_disorder, dtype: int64

In [65]:
df2 = df.copy()

In [66]:
df2['mental_disorder'].replace(to_replace="anxiety",value="stress",inplace=True)

In [67]:
df2['mental_disorder'].value_counts()

depression      153
stress           92
None             30
Panic attack     16
Name: mental_disorder, dtype: int64

In [68]:
s2 = setup(df, target = 'mental_disorder',fix_imbalance=True)

In [69]:
compare_models()

In [70]:
catboost2 = create_model("catboost")

In [78]:
predict_model(catboost2)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.6517
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,depression,0.3110
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.8178
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.5795
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.5193
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.6876
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.6345
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.9844
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.6957
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.6486

In [72]:
grid = {'max_depth': [3,4,5,6,7,8,9],'n_estimators':[10,100, 200, 300]}
tuned_catboost2 = tune_model(catboost2,custom_grid=grid)

In [79]:
predict_model(tuned_catboost2)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.6216
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,None,0.3799
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.6934
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.7530
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.7172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.7710
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.7067
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.9910
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.7449
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.5535

In [76]:
ensemble_catboost2 = ensemble_model(tuned_catboost2)

In [80]:
predict_model(ensemble_catboost2)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.5480
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,None,0.4368
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.7411
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.4713
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.4910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.5092
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.4405
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.9632
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.6333
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.5074

In [73]:
et2 = create_model("et")

In [81]:
predict_model(et2)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.40
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,depression,0.35
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.44
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,depression,0.45
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.43
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.53
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.62
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.43
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.41

In [82]:
tuned_et2 = tune_model(et2)

In [83]:
predict_model(tuned_et2)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.6431
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,stress,0.3840
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.3769
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.3069
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,depression,0.4167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.3898
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,anxiety,0.3440
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.6906
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.3613
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.4462

In [84]:
predict_model(ensemble_et2)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.3980
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,None,0.3120
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.4190
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.3780
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.4600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.3750
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.3410
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.6930
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.4388
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.4040

In [77]:
blender4 = blend_models([catboost2,et2])

In [85]:
predict_model(blender4)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.5259
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,depression,0.3305
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.6289
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.4548
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.4496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.5588
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.5823
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.8022
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.5629
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.5293

In [86]:
blender5 = blend_models([catboost2,ensemble_et2])

In [87]:
predict_model(blender5)

,gender_Female,age_13-19,age_20-26,age_27-33,age_34-44,education_College,education_Professional,education_School,education_Unemployed,education_University,...,thoughts_time_morning,thoughts_time_night,voices_no,harming_others_no,suicide_no,suicidal_thoughts_yes,therapy_no,mental_disorder,Label,Score
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,stress,None,0.5249
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,None,stress,0.3028
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,anxiety,anxiety,0.6184
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,stress,stress,0.4788
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,1.0,depression,anxiety,0.4896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,anxiety,0.5313
84,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,depression,depression,0.4878
85,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,None,None,0.8387
86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Panic attack,depression,0.5673
87,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,None,stress,0.5263

In [88]:
#blender4 is better

In [89]:
s2 = setup(df2, target = 'mental_disorder',fix_imbalance=True)

In [91]:
compare_models()

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=7141, verbose=0,
                     warm_start=False)

In [92]:
et3 = create_model("et")

In [96]:
predict_model(et3)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_yes,harming_others_no,suicide_yes,suicidal_thoughts_yes,therapy_yes,mental_disorder,Label,Score
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.59
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,None,0.42
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,depression,depression,0.70
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,depression,1.00
4,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,Panic attack,stress,0.46
84,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,stress,0.50
85,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,stress,0.69
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,depression,depression,0.42
87,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,None,stress,0.60

In [93]:
tuned_et3 = tune_model(et3)

In [95]:
predict_model(tuned_et3)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_yes,harming_others_no,suicide_yes,suicidal_thoughts_yes,therapy_yes,mental_disorder,Label,Score
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.5536
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,None,0.4958
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,depression,depression,0.7221
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,depression,0.8820
4,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.7579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,Panic attack,stress,0.5041
84,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,stress,0.4380
85,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,stress,0.5459
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,depression,stress,0.4384
87,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,None,stress,0.4905

In [97]:
ensemble_et3 = ensemble_model(et3)

In [98]:
predict_model(ensemble_et3)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_yes,harming_others_no,suicide_yes,suicidal_thoughts_yes,therapy_yes,mental_disorder,Label,Score
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.5750
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,None,0.4990
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,depression,depression,0.7070
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,depression,0.8898
4,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.7337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,Panic attack,stress,0.5210
84,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,stress,0.4670
85,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,stress,0.6050
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,depression,depression,0.4110
87,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,None,stress,0.5420

In [99]:
lda = create_model("lda")

In [100]:
predict_model(lda)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_yes,harming_others_no,suicide_yes,suicidal_thoughts_yes,therapy_yes,mental_disorder,Label,Score
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,depression,depression,1.0000
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,None,1.0000
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,depression,depression,0.9999
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,depression,0.9998
4,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,depression,depression,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,Panic attack,stress,0.9999
84,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,stress,0.7712
85,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,stress,0.9900
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,depression,Panic attack,0.8991
87,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,None,stress,0.8358

In [101]:
tuned_lda = tune_model(lda)

In [102]:
predict_model(tuned_lda)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_yes,harming_others_no,suicide_yes,suicidal_thoughts_yes,therapy_yes,mental_disorder,Label,Score
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,depression,depression,1.0000
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,None,1.0000
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,depression,depression,0.9999
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,depression,0.9998
4,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,depression,depression,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,Panic attack,stress,0.9999
84,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,stress,0.7733
85,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,stress,0.9904
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,depression,Panic attack,0.8984
87,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,None,stress,0.8393

In [103]:
ensemble_lda = ensemble_model(tuned_lda)

In [105]:
blender5 = blend_models([ensemble_et3,tuned_lda])

In [106]:
predict_model(blender5)

,gender_Male,age_13-19,age_20-26,age_27-33,age_34-44,age_45 or more,education_College,education_Professional,education_School,education_Unemployed,...,thoughts_time_morning,thoughts_time_night,voices_yes,harming_others_no,suicide_yes,suicidal_thoughts_yes,therapy_yes,mental_disorder,Label,Score
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.7875
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,None,0.7495
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,depression,depression,0.8534
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,depression,0.9448
4,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,depression,depression,0.8668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,Panic attack,stress,0.7605
84,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,None,stress,0.6202
85,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,stress,stress,0.7977
86,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,depression,Panic attack,0.5282
87,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,None,stress,0.6907

## Trying to fix imbalance